apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "do-next.vatsim-radar.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app-next
                port:
                  number: 3000
